### ISSUE TITLE
Call to undefined function intl_get_error_code

### ISSUE THREAD

**Issue by codetrend104** [flarum-lang/persian#6]
php: 8.3
flarum : 1.8.8

when ever i try to select the perisan language i got "هنگام تلاش برای بارگیری این صفحه خطایی روی داد." in main page and this error in storage/logs

```
[2023-11-15 06:44:32] flarum.ERROR: Error: Call to undefined function Symfony\Component\Translation\Formatter\intl_get_error_code() in /home/parnian/domains/forum.parnianresane.ir/vendor/symfony/translation/Formatter/IntlFormatter.php:43
Stack trace:
#0 /home/parnian/domains/forum.parnianresane.ir/vendor/symfony/translation/Formatter/MessageFormatter.php(54): Symfony\Component\Translation\Formatter\IntlFormatter->formatIntl()
#1 /home/parnian/domains/forum.parnianresane.ir/vendor/symfony/translation/Translator.php(223): Symfony\Component\Translation\Formatter\MessageFormatter->formatIntl()
#2 /home/parnian/domains/forum.parnianresane.ir/vendor/flarum/core/src/Frontend/Driver/BasicTitleDriver.php(40): Symfony\Component\Translation\Translator->trans()
#3 /home/parnian/domains/forum.parnianresane.ir/vendor/flarum/core/src/Frontend/Document.php(221): Flarum\Frontend\Driver\BasicTitleDriver->makeTitle()
#4 /home/parnian/domains/forum.parnianresane.ir/vendor/flarum/core/src/Frontend/Document.php(204): Flarum\Frontend\Document->makeTitle()
#5 /home/parnian/domains/forum.parnianresane.ir/vendor/flarum/core/src/Frontend/Document.php(195): Flarum\Frontend\Document->makeView()
#6 /home/parnian/domains/forum.parnianresane.ir/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Document->render()
#7 /home/parnian/domains/forum.parnianresane.ir/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Frontend\Controller->handle()
#8 /home/parnian/domains/forum.parnianresane.ir/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#9 /home/parnian/domains/forum.parnianresane.ir/vendor/laminas/laminas-stratigility/src/Next.php(52): Flarum\Http\Middleware\ExecuteRoute->process()

```

**Comment by codetrend104** [comment]
thanks, the extension is ok
```
parnian@irvm-759724:~/domains/forum.parnianresane.ir$ sudo apt install php8.3-intl
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
php8.3-intl is already the newest version (8.3.13-1+ubuntu24.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 17 not upgraded.
```

now i'm getting this in the logs
```
//storage/logs/flarum-2024-11-16.log
[2024-11-16 07:46:06] flarum.ERROR: IntlException: pattern syntax error (parse error at offset 1, after "{", before or at "ﺶﻣﺍﺮﻫ ﺺﻔﺤﻫ،ﺞﻤﻋ،"): U_PATTERN_SYNTAX_ERROR in /home/parnian/domains/forum.parnianresane.ir/vendor/symfony/translation/Formatter/IntlFormatter.php:41
Stack trace:
#0 /home/parnian/domains/forum.parnianresane.ir/vendor/symfony/translation/Formatter/IntlFormatter.php(41): MessageFormatter->__construct()
#1 /home/parnian/domains/forum.parnianresane.ir/vendor/symfony/translation/Formatter/MessageFormatter.php(54): Symfony\Component\Translation\Formatter\IntlFormatter->formatIntl()
#2 /home/parnian/domains/forum.parnianresane.ir/vendor/symfony/translation/Translator.php(223): Symfony\Component\Translation\Formatter\MessageFormatter->formatIntl()
#3 /home/parnian/domains/forum.parnianresane.ir/vendor/flarum/core/src/Frontend/Driver/BasicTitleDriver.php(40): Symfony\Component\Translation\Translator->trans()



Next Symfony\Component\Translation\Exception\InvalidArgumentException: Invalid message format (error #65799): pattern syntax error (parse error at offset 1, after "{", before or at "ﺶﻣﺍﺮﻫ ﺺﻔﺤﻫ،ﺞﻤﻋ،"): U_PATTERN_SYNTAX_ERROR in /home/parnian/domains/forum.parnianresane.ir/vendor/symfony/translation/Formatter/IntlFormatter.php:43
Stack trace:
#0 /home/parnian/domains/forum.parnianresane.ir/vendor/symfony/translation/Formatter/MessageFormatter.php(54): Symfony\Component\Translation\Formatter\IntlFormatter->formatIntl()
#1 /home/parnian/domains/forum.parnianresane.ir/vendor/symfony/translation/Translator.php(223): Symfony\Component\Translation\Formatter\MessageFormatter->formatIntl()
#2 /home/parnian/domains/forum.parnianresane.ir/vendor/flarum/core/src/Frontend/Driver/BasicTitleDriver.php(40): Symfony\Component\Translation\Translator->trans()
#3 /home/parnian/domains/forum.parnianresane.ir/vendor/flarum/core/src/Frontend/Document.php(221): Flarum\Frontend\Driver\BasicTitleDriver->makeTitle()
#4 /home/parnian/domains/forum.parnianresane.ir/vendor/flarum/core/src/Frontend/Document.php(204): Flarum\Frontend\Document->makeTitle()
```

**Comment by codetrend104** [comment]
And i tried to restart the php and nginx services
`sudo service nginx restart`  
`sudo service php8.3-fpm restart`

but still same error, any other extension needed?

**Comment by codetrend104** [comment]
دست شما درد نکنه.
